Bootstrap: docker
From: ubuntu:18.04

%files
../../cluster/* /opt/

%labels
maintainer jfunke@iri.upc.edu

%post

apt update
apt install -y --no-install-recommends \
build-essential \
ca-certificates \
cmake \
git \
wget \
libboost-all-dev && \
rm -rf /var/lib/apt/lists/*

# install conda

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p /miniconda
PATH="/miniconda/bin:$PATH"
conda config --set always_yes yes --set changeps1 no
conda update -q conda
conda info -a
conda install python=3.6

# install tensorflow

conda install tensorflow-gpu=1.3

# install dependencies for gunpowder

# malis
MALIS_ROOT=/src/malis
MALIS_REPOSITORY=https://github.com/TuragaLab/malis.git
MALIS_REVISION=2206fe01bd2d10c3bc6a861897820731d1ae131b

pip install cython
mkdir -p ${MALIS_ROOT}
cd ${MALIS_ROOT}
git clone ${MALIS_REPOSITORY} . && \
git checkout ${MALIS_REVISION}
python setup.py build_ext --inplace
PYTHONPATH=${MALIS_ROOT}:$PYTHONPATH

# augment
AUGMENT_ROOT=/src/augment
AUGMENT_REPOSITORY=https://github.com/funkey/augment.git
AUGMENT_REVISION=4a42b01ccad7607b47a1096e904220729dbcb80a

mkdir -p ${AUGMENT_ROOT}
cd ${AUGMENT_ROOT}
git clone ${AUGMENT_REPOSITORY} . && \
git checkout ${AUGMENT_REVISION}
pip install -r requirements.txt
PYTHONPATH=${AUGMENT_ROOT}:$PYTHONPATH

# waterz
WATERZ_ROOT=/src/waterz
WATERZ_REPOSITORY=https://github.com/funkey/waterz
WATERZ_REVISION=d2bede846391c56a54365c13d5b2f2f4e6db4ecd

mkdir -p ${WATERZ_ROOT}
cd ${WATERZ_ROOT}
git clone ${WATERZ_REPOSITORY} . && \
git checkout ${WATERZ_REVISION}
mkdir -p /.cython/inline
PYTHONPATH=${WATERZ_ROOT}:$PYTHONPATH

# install gunpowder

GUNPOWDER_ROOT=/src/gunpowder
GUNPOWDER_REPOSITORY=https://github.com/funkey/gunpowder.git
# GUNPOWDER_REVISION=d58dd5f5946368dc5eeb4fd58cb3a0f0c9dc4d12
# below is on branch reject_on_points
GUNPOWDER_REVISION=023996a48e1305f7638b283e1247e79db050908c

mkdir -p ${GUNPOWDER_ROOT}
cd ${GUNPOWDER_ROOT}
git clone ${GUNPOWDER_REPOSITORY} . && \
git checkout ${GUNPOWDER_REVISION}
pip install -r requirements.txt
PYTHONPATH=${GUNPOWDER_ROOT}:$PYTHONPATH

# install pylp and gurobi

conda install -c funkey pylp

%environment
export MALIS_ROOT=/src/malis
export MALIS_REPOSITORY=https://github.com/TuragaLab/malis.git
export MALIS_REVISION=2206fe01bd2d10c3bc6a861897820731d1ae131b
export AUGMENT_ROOT=/src/augment
export AUGMENT_REPOSITORY=https://github.com/funkey/augment.git
export AUGMENT_REVISION=4a42b01ccad7607b47a1096e904220729dbcb80a
export WATERZ_ROOT=/src/waterz
export WATERZ_REPOSITORY=https://github.com/funkey/waterz
export WATERZ_REVISION=d2bede846391c56a54365c13d5b2f2f4e6db4ecd
export PYTHONPATH=${MALIS_ROOT}:$PYTHONPATH
export PYTHONPATH=${AUGMENT_ROOT}:$PYTHONPATH
export PYTHONPATH=${WATERZ_ROOT}:$PYTHONPATH
export PYTHONPATH=/src/gunpowder:$PYTHONPATH
export PATH=/miniconda/bin:$PATH

%runscript
exec /bin/bash "$@"
