Bootstrap: docker
From: tensorflow/tensorflow:1.3.0-gpu

%files
../../cluster/* /opt/

%labels
maintainer jfunke@iri.upc.edu

%post

apt-get update && apt-get install -y --no-install-recommends \
build-essential \
cmake \
git \
libboost-all-dev \
python-dev \
python-numpy \
python-pip \
python-setuptools \
python-scipy && \
rm -rf /var/lib/apt/lists/*

pip install --upgrade pip

# install dependencies for gunpowder

# malis
MALIS_ROOT=/src/malis
MALIS_REPOSITORY=https://github.com/TuragaLab/malis.git
MALIS_REVISION=2206fe01bd2d10c3bc6a861897820731d1ae131b

pip install cython
mkdir -p ${MALIS_ROOT}
cd ${MALIS_ROOT}
git clone ${MALIS_REPOSITORY} . && \
git checkout ${MALIS_REVISION}
python setup.py build_ext --inplace
PYTHONPATH=${MALIS_ROOT}:$PYTHONPATH

# augment
AUGMENT_ROOT=/src/augment
AUGMENT_REPOSITORY=https://github.com/funkey/augment.git
AUGMENT_REVISION=4a42b01ccad7607b47a1096e904220729dbcb80a

mkdir -p ${AUGMENT_ROOT}
cd ${AUGMENT_ROOT}
git clone ${AUGMENT_REPOSITORY} . && \
git checkout ${AUGMENT_REVISION}
pip install -r requirements.txt
PYTHONPATH=${AUGMENT_ROOT}:$PYTHONPATH

# dvision
DVISION_ROOT=/src/dvision
DVISION_REPOSITORY=https://github.com/TuragaLab/dvision.git
DVISION_REVISION=v0.1.1

mkdir -p ${DVISION_ROOT}
cd ${DVISION_ROOT}
git clone -b ${DVISION_REVISION} --depth 1 ${DVISION_REPOSITORY} .
pip install -r requirements.txt
PYTHONPATH=${DVISION_ROOT}:$PYTHONPATH

# waterz
WATERZ_ROOT=/src/waterz
WATERZ_REPOSITORY=https://github.com/funkey/waterz
WATERZ_REVISION=d2bede846391c56a54365c13d5b2f2f4e6db4ecd

mkdir -p ${WATERZ_ROOT}
cd ${WATERZ_ROOT}
git clone ${WATERZ_REPOSITORY} . && \
git checkout ${WATERZ_REVISION}
mkdir -p /.cython/inline
PYTHONPATH=${WATERZ_ROOT}:$PYTHONPATH

# install gunpowder

GUNPOWDER_ROOT=/src/gunpowder
GUNPOWDER_REPOSITORY=https://github.com/funkey/gunpowder.git
# GUNPOWDER_REVISION=d58dd5f5946368dc5eeb4fd58cb3a0f0c9dc4d12
# below is on branch reject_on_points
GUNPOWDER_REVISION=023996a48e1305f7638b283e1247e79db050908c

mkdir -p ${GUNPOWDER_ROOT}
cd ${GUNPOWDER_ROOT}
git clone ${GUNPOWDER_REPOSITORY} . && \
git checkout ${GUNPOWDER_REVISION}
pip install -r requirements.txt
PYTHONPATH=${GUNPOWDER_ROOT}:$PYTHONPATH

# install pylp and gurobi

cd /opt
tar xfz gurobi8.1.0_linux64.tar.gz
GUROBI_ROOT_DIR=/opt/gurobi810/linux64
cd ${GUROBI_ROOT_DIR}
python setup.py install
export GUROBI_ROOT_DIR=/opt/gurobi810/linux64

PYLP_ROOT=/src/pylp
PYLP_REPOSITORY=https://github.com/funkey/pylp
PYLP_REVISION=51112ba453c361e6980d7c8b24faace2bd7c8064

mkdir -p ${PYLP_ROOT}
cd ${PYLP_ROOT} 
git clone ${PYLP_REPOSITORY} . && \
git checkout ${PYLP_REVISION} && \
git submodule update --init
python setup.py install

%environment
export MALIS_ROOT=/src/malis
export MALIS_REPOSITORY=https://github.com/TuragaLab/malis.git
export MALIS_REVISION=2206fe01bd2d10c3bc6a861897820731d1ae131b
export AUGMENT_ROOT=/src/augment
export AUGMENT_REPOSITORY=https://github.com/funkey/augment.git
export AUGMENT_REVISION=4a42b01ccad7607b47a1096e904220729dbcb80a
export DVISION_ROOT=/src/dvision
export DVISION_REPOSITORY=https://github.com/TuragaLab/dvision.git
export DVISION_REVISION=v0.1.1
export WATERZ_ROOT=/src/waterz
export WATERZ_REPOSITORY=https://github.com/funkey/waterz
export WATERZ_REVISION=d2bede846391c56a54365c13d5b2f2f4e6db4ecd
export PYTHONPATH=${MALIS_ROOT}:$PYTHONPATH
export PYTHONPATH=${AUGMENT_ROOT}:$PYTHONPATH
export PYTHONPATH=${DVISION_ROOT}:$PYTHONPATH
export PYTHONPATH=${WATERZ_ROOT}:$PYTHONPATH
export PYTHONPATH=/src/gunpowder:$PYTHONPATH

%runscript
exec /bin/bash "$@"
