Bootstrap: docker
From: funkey/gunpowder:v0.3.2

%help
This container contains linajea lineage tracking software.

%labels

    Maintainer Jan Funke
    Version 0.1


%setup
mkdir -p ${SINGULARITY_ROOTFS}/src/linajea

%files
../linajea /src/linajea/linajea
../requirements.txt /src/linajea/requirements.txt
../setup.py /src/linajea/setup.py
../cluster /opt

%labels
maintainer funkej@janelia.hhmi.org

%post

# install pylp and gurobi
cd /opt
tar xvfz gurobi8.1.0_linux64.tar.gz
GUROBI_ROOT_DIR=/opt/gurobi810/linux64
cd ${GUROBI_ROOT_DIR}
python setup.py install

PYLP_ROOT=/src/pylp
PYLP_REPOSITORY=https://github.com/funkey/pylp
PYLP_REVISION=51112ba453c361e6980d7c8b24faace2bd7c8064

mkdir -p ${PYLP_ROOT}
cd ${PYLP_ROOT} 
git clone ${PYLP_REPOSITORY} . && \
git checkout ${PYLP_REVISION} && \
git submodule update --init
python setup.py install

# install jupyter and nyroglancer

pip install --upgrade --ignore-installed notebook

NYROGLANCER_ROOT=/src/nyroglancer
NYROGLANCER_REPOSITORY=https://github.com/funkey/nyroglancer
NYROGLANCER_REVISION=984781dd6acf4235dde33568a89c0043efd52652

mkdir -p ${NYROGLANCER_ROOT}
cd ${NYROGLANCER_ROOT}
git clone ${NYROGLANCER_REPOSITORY} . && \
git checkout ${NYROGLANCER_REVISION}
PYTHONPATH=${NYROGLANCER_ROOT}:$PYTHONPATH

NEUROGLANCER_ROOT=/src/neuroglancer
NEUROGLANCER_REPOSITORY=https://github.com/google/neuroglancer
NEUROGLANCER_REVISION=253a5cc

mkdir -p ${NEUROGLANCER_ROOT}
cd ${NEUROGLANCER_ROOT}
git clone ${NEUROGLANCER_REPOSITORY} . && \
git checkout ${NEUROGLANCER_REVISION}
cd ${NEUROGLANCER_ROOT}/python
python setup.py install

# install dependencies

# install python wrapper for KLB reader
PYKLB_ROOT=/src/pyklb
PYKLB_REPOSITORY=https://github.com/bhoeckendorf/pyklb
PYKLB_REVISION=870874e26129411382323467d62038456bcb0385

pip install wheel
mkdir -p ${PYKLB_ROOT}
cd ${PYKLB_ROOT}
git clone ${PYKLB_REPOSITORY} . && \
git checkout ${PYKLB_REVISION}
python setup.py bdist_wheel
PYTHONPATH=${PYKLB_ROOT}/build/lib.linux-x86_64-2.7:${PYTHONPATH}
cp build/lib/libklb.so /lib

DAISY_ROOT=/src/daisy
DAISY_REPOSITORY=https://github.com/funkey/daisy
DAISY_REVISION=dc14ee3d5395d9ec2bcaca032d7ed5c5d97f8c70

mkdir -p ${DAISY_ROOT}
cd ${DAISY_ROOT}
git clone ${DAISY_REPOSITORY} . && \
git checkout ${DAISY_REVISION}
PYTHONPATH=${DAISY_ROOT}:$PYTHONPATH

COMATCH_ROOT=/src/comatch
COMATCH_REPOSITORY=https://github.com/funkey/comatch
# master
COMATCH_REVISION=193ca3072ae27666c54939f4bb0a4911404f33d7
# quadmatch
#COMATCH_REVISION=fa7c9e3ea9f9b5ddc2fb74654378d696b7a14b35

mkdir -p ${COMATCH_ROOT}
cd ${COMATCH_ROOT}
git clone ${COMATCH_REPOSITORY} . && \
git checkout ${COMATCH_REVISION}
python setup.py install

pip install zarr networkx pymongo
pip install dask distributed --upgrade

# install linajea

cd /src/linajea
python setup.py install

pip install plotly

%environment
export NYROGLANCER_ROOT=/src/nyroglancer
export NYROGLANCER_REPOSITORY=https://github.com/funkey/nyroglancer
export NYROGLANCER_REVISION=984781dd6acf4235dde33568a89c0043efd52652
export PYTHONPATH=${NYROGLANCER_ROOT}:$PYTHONPATH
export NEUROGLANCER_ROOT=/src/neuroglancer
export NEUROGLANCER_REPOSITORY=https://github.com/google/neuroglancer
export NEUROGLANCER_REVISION=253a5cc
export PYKLB_ROOT=/src/pyklb
export PYKLB_REPOSITORY=https://github.com/bhoeckendorf/pyklb
export PYKLB_REVISION=870874e26129411382323467d62038456bcb0385
export PYTHONPATH=${PYKLB_ROOT}/build/lib.linux-x86_64-2.7:${PYTHONPATH}
export DAISY_ROOT=/src/daisy
export DAISY_REPOSITORY=https://github.com/funkey/daisy
export DAISY_REVISION=dc14ee3d5395d9ec2bcaca032d7ed5c5d97f8c70
export PYTHONPATH=${DAISY_ROOT}:$PYTHONPATH
export GRB_LICENSE_FILE=/opt/gurobi.lic
export GUROBI_ROOT_DIR=/opt/gurobi810/linux64

%runscript
exec /bin/bash "$@"
