Bootstrap: localimage
From: /nrs/funke/singularity/linajea/pylp_base:v1.5.img

%help
This container contains linajea lineage tracking software.

%labels

Maintainer Jan Funke
Name linajea

%setup
mkdir -p ${SINGULARITY_ROOTFS}/src/linajea

%files
../linajea /src/linajea/linajea
../requirements.txt /src/linajea/requirements.txt
../setup.py /src/linajea/setup.py

%labels
maintainer funkej@janelia.hhmi.org

%post

PATH="/miniconda/bin:$PATH"

# install gunpowder

GUNPOWDER_ROOT=/src/gunpowder
GUNPOWDER_REPOSITORY=https://github.com/funkey/gunpowder.git
GUNPOWDER_REVISION=767e52657ac703f6f23b88a7dbd7294315d60684

mkdir -p ${GUNPOWDER_ROOT}
cd ${GUNPOWDER_ROOT}
git clone ${GUNPOWDER_REPOSITORY} . && \
git checkout ${GUNPOWDER_REVISION}
pip install -r requirements.txt
PYTHONPATH=${GUNPOWDER_ROOT}:$PYTHONPATH

# install linajea dependencies

DAISY_ROOT=/src/daisy
DAISY_REPOSITORY=https://github.com/funkey/daisy
DAISY_REVISION=f4e2dced0eaac6c427e76f27743f6ca242a93e49

mkdir -p ${DAISY_ROOT}
cd ${DAISY_ROOT}
git clone ${DAISY_REPOSITORY} . && \
git checkout ${DAISY_REVISION}
pip install -r requirements.txt
pip install .

COMATCH_ROOT=/src/comatch
COMATCH_REPOSITORY=https://github.com/funkey/comatch
COMATCH_REVISION=193ca3072ae27666c54939f4bb0a4911404f33d7

mkdir -p ${COMATCH_ROOT}
cd ${COMATCH_ROOT}
git clone ${COMATCH_REPOSITORY} . && \
git checkout ${COMATCH_REVISION}
python setup.py install

# install linajea

cd /src/linajea
pip install -r requirements.txt
python setup.py install

pip install plotly

%environment
export DAISY_ROOT=/src/daisy
export PYTHONPATH=${DAISY_ROOT}:$PYTHONPATH
export GUNPOWDER_ROOT=/src/gunpowder
export PYTHONPATH=${GUNPOWDER_ROOT}:$PYTHONPATH
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

%runscript
exec /bin/bash "$@"
